// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Calculator.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
//using namespace ::apache::thrift::client;

using boost::shared_ptr;

int main(int argc, char **argv) {
  shared_ptr<TTransport> tTransport(new TSocket("localhost", 9090));
  shared_ptr<TBinaryProtocol> tBinPr(new TBinaryProtocol(tTransport));
  shared_ptr<CalculatorClient> client(new CalculatorClient(tBinPr));
  tTransport->open();
  printf("%d\n", client->add(0xFF, 10));
  return 0;
}

